# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Abdulrahman Suleiman
first_name: Abdulrahman
middle_name:
last_name: Suleiman
email: s.abdurrahman6666@gmail.com
description: Software Engineering undergraduate focusing on AI Security and Adversarial Machine Learning.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: ai-security, adversarial-machine-learning, automated-program-analysis, cybersecurity

# Profile address
country_code: NG
city: Abuja

# URL structure
url: "https://realavdulmouhd.github.io"
baseurl: ""

# Social & Research Profiles
socials:
  email: s.abdurrahman6666@gmail.com
  github: Realavdulmouhd
  linkedin: realavdulmouhd-abdulrahman-suleiman
  orcid: 0009-0008-8213-2555
  x: real_avdulmouhd
  facebook: realavdulmouhd
